### ISSUE TITLE
How should this be used together with sqlx?

### ISSUE THREAD

**Issue by ptman** [simukti/sqldb-logger#47]
https://github.com/jmoiron/sqlx

**Comment by simukti** [comment]
@ptman I'm on mobile browser now, but having quick look at sqlx code, sqlx accept `*sql.DB`, so you can just pass  `*sql.DB` ([from sqldb-logger](https://github.com/simukti/sqldb-logger/blob/master/README.md#usage)) to sqlx [`NewDb`](https://github.com/jmoiron/sqlx/blob/ee514944af4b0d1b90212831674e03df1b850998/sqlx.go#L255) and it should good to go.
